### ISSUE TITLE
Does not work in Sublime Text 3 in Linux

### ISSUE THREAD

**Issue by gamedev8** [gomobile/sublime-xdk-package#1]
This is the error in the Sublime Text 3 log

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "commands in /opt/sublime_text/Packages/XDK.sublime-package", line 27, in run
  File "XDKCore in /opt/sublime_text/Packages/XDK.sublime-package", line 217, in prepare
  File "XDKCore in /opt/sublime_text/Packages/XDK.sublime-package", line 208, in find_xdk_installation
  File "XDKCore in /opt/sublime_text/Packages/XDK.sublime-package", line 143, in get_data_path
  File "./posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by likhter** [comment]
@gamedev8 could you give steps to reproduce?

**Comment by gamedev8** [comment]
Just install the plugin and then open sublime. None of the XDK menu options will be functional, and the error shows up in the console.

**Comment by likhter** [comment]
Please note that we fixed a bit installation steps for linux
