### ISSUE TITLE
Plugins doesn't work at all

### ISSUE THREAD

**Issue by lukaszkups** [gomobile/sublime-xdk-package#3]
Hi!

I've just installed intel xdk package via package manager to my Sublime Text 3 on linux (elementary OS). I have also Intel XDK itself installed - and it works fine.

The problem is, that this plugin doesn't work at all - I've tried with Intel XDK launched and closed, with App Preview and without it, but without success. None of the options in Sublime Text dedicated to this plugin doesn't work - I just click and nothing happens - no erros, anything - is this package still supported? (I saw that last commit was done year ago)

Edit: I've found those logs in Sublime's console:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "commands in /home/lkups/.config/sublime-text-3/Installed Packages/IntelXDK.sublime-package", line 28, in run
  File "commands in /home/lkups/.config/sublime-text-3/Installed Packages/IntelXDK.sublime-package", line 104, in prepare_data
  File "XDKCore in /home/lkups/.config/sublime-text-3/Installed Packages/IntelXDK.sublime-package", line 239, in prepare_request_data
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by xmnboy** [comment]
This plugin has not been updated for quite some time, and the internal interfaces in the XDK on which it relies have changed during that time. The plugin is in the process of being "taken down" due to this lack of support and will be retired soon.
